name: oppgave 15

on: 
  -pus
  -workflow_dispatch

jobs:
  job1:
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: action/checkout@v2

      - name: Run Blackjack script file
        run: ./src/oppgave_10.ps1